### ISSUE TITLE
Data hard to see when showing scenarios

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/ForecastHubSubmissionApp#14]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/1156307/182334587-19bf1c92-d385-40dc-8ae0-6832f5195b8e.png">

vs. 

<img width="996" alt="image" src="https://user-images.githubusercontent.com/1156307/182334698-8ac48fd1-c6e2-4f18-ae9e-919bfff36639.png">

Is there an easy fix?

**Comment by Bisaloo** [comment]
What do you mean? I would expect this behaviour for samples with low variability

**Comment by sbfnk** [comment]
Sorry, that wasn't very clear. I meant the "truth" bit (period from end of June in top plot).

**Comment by Bisaloo** [comment]
Fixed by 4c2ed8f.
